=== alexprometeo/lm_asir/2da_Eva/XML/02_contactos/contactos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="contactos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="apellidos" type="xs:string"></xs:element>
                            <xs:element name="correo" type="xs:string"></xs:element>
                            <xs:element name="telefono" type="xs:integer"></xs:element>  
                            <xs:element name="direccion" type="xs:string"></xs:element>                            
                        </xs:sequence>
                        <xs:attribute name="genero">
                            <xs:simpleType >
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="O"></xs:enumeration>
                                    <xs:enumeration value="F"></xs:enumeration>
                                    <xs:enumeration value="M"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alexprometeo/lm_asir/2da_Eva/XML/02_contactos/contactos.xml
<?xml version="1.0" encoding="UTF-8"?> 

<!-- Enlazar DTD -->
<!-- <?xml-model href="contactos.dtd"?> -->

<contactos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="contactos.xsd">
    <persona genero="M">
        <nombre>Pepe</nombre>
        <apellidos>Ruiz</apellidos>
        <correo>pepe@mail.com</correo>
        <telefono>555123654</telefono>
        <direccion>C/Falsa 123</direccion>
    </persona>

    <persona genero="O">
        <nombre>Ana</nombre>
        <!-- CDATA se utilizar para escapar cierta información que no queremos que los programas lectores de XML -->
        <apellidos><![CDATA[Fernandez]]></apellidos>
        <correo>ana@mail.com</correo>
        <telefono>987654321</telefono>
        <direccion>C/Piruleta 32</direccion>
    </persona>    
</contactos>

 <!-- 
    XML con el elemento padre contactos;
        dentro de contactos tendrá elementos persona
        (deberá tener el atributo género)
        con los siguientes elementos:
            - nombre 
            - apellidos
            - correo
            - teléfono
            - dirección
 -->
